apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-telegram.fullname" . }}
  labels:
    {{- include "mautrix-telegram.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: mautrix-telegram
